"""Initial schema — source, snapshot, change tables.

Hand-written migration (NOT autogenerated) so that:
- The source.health_status CHECK constraint is guaranteed present.
- The change.status CHECK constraint (6 values) is guaranteed present.
- The snapshot UNIQUE(source_id, version) constraint is guaranteed present.
- The idx_change_status and idx_change_updated_at indexes are guaranteed present.

Alembic autogenerate routinely omits CheckConstraints and composite Indexes;
the initial migration must not rely on a human noticing the omission
(review finding #19).

Revision ID: 0001
Revises:
Create Date: 2026-05-21
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# ---------------------------------------------------------------------------
# Alembic metadata
# ---------------------------------------------------------------------------

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ------------------------------------------------------------------
    # source — rule-source registry
    # ------------------------------------------------------------------
    op.create_table(
        "source",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("jurisdiction", sa.String(), nullable=False),
        sa.Column("layer", sa.String(), nullable=False),
        sa.Column("feed_url", sa.String(), nullable=False),
        sa.Column("ingestion_method", sa.String(), nullable=False),
        sa.Column("adapter_ref", sa.String(), nullable=False),
        sa.Column("polling_cadence", sa.String(), nullable=False),
        sa.Column("last_checked_at", sa.DateTime(), nullable=True),
        sa.Column("last_changed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "health_status",
            sa.String(),
            nullable=False,
            server_default="unknown",
        ),
        sa.Column("last_etag", sa.String(), nullable=True),
        sa.Column("last_modified_http", sa.String(), nullable=True),
        sa.Column("last_content_hash", sa.String(), nullable=True),
        sa.Column("tenant_id", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        # Typed health-status CHECK constraint (review finding #20).
        sa.CheckConstraint(
            "health_status IN ('unknown', 'healthy', 'failed')",
            name="ck_source_health_status",
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # ------------------------------------------------------------------
    # snapshot — append-only versioned content store
    # ------------------------------------------------------------------
    op.create_table(
        "snapshot",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["source.id"], name="fk_snapshot_source_id"
        ),
        sa.PrimaryKeyConstraint("id"),
        # UNIQUE(source_id, version) — turns the version-number race into a
        # hard DB error so concurrent inserts fail cleanly (review finding #5).
        sa.UniqueConstraint(
            "source_id", "version", name="uq_snapshot_source_version"
        ),
    )

    # Index to speed up max(version) look-ups during store_snapshot.
    op.create_index(
        "idx_snapshot_source_id",
        "snapshot",
        ["source_id"],
    )

    # ------------------------------------------------------------------
    # change — detected rule-change record
    # ------------------------------------------------------------------
    op.create_table(
        "change",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("prior_snapshot_id", sa.Integer(), nullable=True),
        sa.Column("current_snapshot_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.String(),
            nullable=False,
            server_default="detected",
        ),
        # EFF-01 — detected_at (NOT NULL) and effective_date (Date, NULLABLE).
        sa.Column("detected_at", sa.DateTime(), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.Column("diff_text", sa.Text(), nullable=True),
        # JSONB columns — structured AI summary and summary-failure details.
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("summary_error", sa.Text(), nullable=True),
        sa.Column("not_legal_advice_label", sa.String(), nullable=True),
        sa.Column("reviewer_name", sa.String(), nullable=True),
        sa.Column("model_id", sa.String(), nullable=True),
        sa.Column("tenant_id", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["source.id"], name="fk_change_source_id"
        ),
        sa.ForeignKeyConstraint(
            ["prior_snapshot_id"],
            ["snapshot.id"],
            name="fk_change_prior_snapshot_id",
        ),
        sa.ForeignKeyConstraint(
            ["current_snapshot_id"],
            ["snapshot.id"],
            name="fk_change_current_snapshot_id",
        ),
        # Status CHECK constraint — 6 values exactly (VARCHAR not native PG ENUM;
        # see RESEARCH Pitfall 5 — taxonomy will gain values in Phases 5/6).
        sa.CheckConstraint(
            "status IN ("
            "'detected', 'processed', 'summary_failed', "
            "'in_review', 'verified', 'rejected'"
            ")",
            name="ck_change_status",
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # Index on status — every review-queue and pull-API query filters on it
    # (review finding #21 — avoids table scan as the table grows).
    op.create_index(
        "idx_change_status",
        "change",
        ["status"],
    )

    # Index on updated_at — backs the since-cursor incremental pull-API query.
    op.create_index(
        "idx_change_updated_at",
        "change",
        ["updated_at"],
    )


def downgrade() -> None:
    op.drop_index("idx_change_updated_at", table_name="change")
    op.drop_index("idx_change_status", table_name="change")
    op.drop_table("change")
    op.drop_index("idx_snapshot_source_id", table_name="snapshot")
    op.drop_table("snapshot")
    op.drop_table("source")
